services:
  - type: web
    name: n8n
    env: docker
    plan: free
    envVars:
      - key: N8N_PORT
        value: 10000
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: N8nadminme
      
      - key: N8N_ENCRYPTION_KEY
        value: 1f9a6ae5698b30c48b8a706bb67b58164d4b8bc41522279c191f292195b5bb41
      - key: DB_TYPE
        value: sqlite
